### ISSUE TITLE
sasjs lint requirements

### ISSUE THREAD

**Issue by allanbowe** [sasjs/vscode-extension#11]
- [x] trailing space removed
 - [ ] tabs converted to (2) spaces
 - [ ] lines over 80 characters (warning, not error)
 - [ ] filenames should be lowercase, no spaces
 - [ ] doxygen header added - file should always start `/**` then header until `**/`
 - [ ] Presence of passwords such as {SAS002} or {SAS001} 
 - [ ] Macro names lower case (so, `%macro somename` instead of `%macro SOMENAME`)
 - [ ] Doxy header `  <h4> Data Inputs </h4>`  instead of ` <h4> Data Inputs </h4>` (should be 2 leading spaces)
 - [ ] Same for `@li` sub items
 - [ ] NO INVISIBLES! (except spaces, CR / LF, and if necessary, tabs)

**Comment by krishna-acondy** [comment]
I've copied the list over to https://github.com/sasjs/lint/issues/1.
Closing this one.
