### ISSUE TITLE
Run linter w/o SAS

### ISSUE THREAD

**Issue by savian-net** [sasjs/vscode-extension#24]
I installed it in VSCode, I do not have SAS installed, but I tried to run it. The extension asked for a my SAS setup but I just wanted to test the linter.

Any chance you can just run the linter separately?

**Comment by allanbowe** [comment]
You don't need to click the running man icon - the linter executed automatically.

Just open the terminal, you have several tabs, the left hand one ("problems") shows the lint results

eg:

![Uploading image.png…]()

**Comment by allanbowe** [comment]
The alternative way to execute is with the CLI.  First, install Node JS.  Then, `npm i -g @sasjs/cli`.  Finally you can run `sasjs lint`

**Comment by allanbowe** [comment]
I updated the documentation in the README:  https://github.com/sasjs/vscode-extension/blob/main/README.md#sas-lint

**Comment by allanbowe** [comment]
Closing. To clarify:

* The extension does not require SAS, nor do you need to connect to SAS
* The linting feature is used by clicking View then Problems (or CTRL/SHIFT/M)
* The lint can also be performed by running `sasjs lint` after installing with `npm i -g @sasjs/cli` (not related to the VS Code extension though)
