### ISSUE TITLE
Could not get pop up's in VS Code editor to enter Envrionment , client id and password

### ISSUE THREAD

**Issue by venkattoluchuri** [sasjs/vscode-extension#271]

**Comment by allanbowe** [comment]
Hi @venkattoluchuri - can you try just removing your ~/.sasjsrc file?

**Comment by allanbowe** [comment]
@venkattoluchuri - we have refactored this part in the latest release (1.13.1).  Am closing this ticket but if you are having problems feel free to comment or raise a new one.
