### ISSUE TITLE
example ~/.sasjsrc for SASjs Server on Windows 

### ISSUE THREAD

**Issue by jbodart-argenx** [sasjs/vscode-extension#347]
according to [VS Code extension page](https://marketplace.visualstudio.com/items?itemName=SASjs.sasjs-for-vscode):

> The target 🎯 describes the server on which you intend to run the code. The attributes are added to a file in your home directory - ~/.sasjsrc. More info [here](https://cli.sasjs.io/faq/#what-is-the-difference-between-local-and-global-targets)).

> 
> The following attributes are needed for all server types:

> 
> **Name**. An alias to represent the target.
> **Server Url**. The full URL (including port if needed) of your SAS server.
> **Server Type**. Can be SASVIYA, SAS9 or SASJS.

Could you please provide an example of `~/.sasjsrc` file showing _how to specify_ **Name** (MySASjs), **Server Url** (http://localhost:5000/) and **Server Type** (SASJS) for SAS BASE desktop?

**Comment by allanbowe** [comment]
Absolutely - please note that a pre-requisite is to install [SASjs Server](https://server.sasjs.io) which provides the REST API against your SAS executable.

If you have SASjs Server running (you can submit code in Studio and get a log back) then you can configure the target

The easiest way to do this is to just click the target icon and follow the prompts (using `clientID1` for the client)

<img width="1022" alt="Screenshot 2022-09-08 at 15 35 06" src="https://user-images.githubusercontent.com/4420615/189150667-def6aaf7-9ad5-4332-a233-0b2748697325.png">

Ultimately, your `.sasjsrc` will look like this:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/4420615/189150900-5fa66bf5-e21d-42b3-8dc8-107eda3e1bdc.png">

If you are having issues I'd be happy to jump on a call to assist:  https://4gl.uk/book

**Comment by jbodart-argenx** [comment]
Ok I was able to create a target, and ended up with the following `~/.sasjsrc` file:

```
{
  "targets": [
    {
      "name": "SAS94",
      "serverUrl": "http://localhost:5000",
      "serverType": "SASJS",
      "appLoc": "/Public/app",
      "buildConfig": {
        "initProgram": "",
        "termProgram": "",
        "buildOutputFileName": "SAS94.sas",
        "buildOutputFolder": "sasjsbuild",
        "buildResultsFolder": "sasjsresults",
        "macroVars": {}
      },
      "jobConfig": {
        "jobFolders": [],
        "initProgram": "",
        "termProgram": "",
        "macroVars": {}
      },
      "serviceConfig": {
        "serviceFolders": [],
        "initProgram": "",
        "termProgram": "",
        "macroVars": {}
      },
      "streamConfig": {
        "streamWebFolder": "",
        "streamWeb": false,
        "webSourcePath": "",
        "streamServiceName": "",
        "assetPaths": []
      },
      "deployConfig": {
        "deployScripts": [],
        "deployServicePack": false
      },
      "testConfig": {
        "initProgram": "",
        "termProgram": "",
        "macroVars": {},
        "testSetUp": "",
        "testTearDown": ""
      }
    }
  ]
}
```

**Comment by jbodart-argenx** [comment]
is the `SAS_OPTIONS` setting in `..\sasjs-0.19.0\.env` file overriden by the environment variable `SAS_OPTIONS` ?

**Comment by allanbowe** [comment]
Great!  No you are right, there is no authConfig in desktop mode.

About the SAS_OPTIONS - in fact, all it does is create the environment variable.  It does not add it to the launch command.

You can see the launch command in the server log under sasjs_root.

Can you try it without the quote marks?

**Comment by jbodart-argenx** [comment]
I can see multiple .log files e.g. `20220908154741.log` under `..\sasjs-0.19.0\sasjs_root\logs` (witch lines like: `::ffff:127.0.0.1 - - [08/Sep/2022:15:08:50 +0000] "POST /SASjsApi/code/execute HTTP/1.1" 200 7275`) and multiple folders under `..\sasjs-0.19.0\sasjs_root\sessions\` containing a file named `log.log` (looks like SAS log) ...
but I can't file any call to `sas.exe`

I tried without success
```
SAS_OPTIONS=-CONFIG C:\Users\jbodart\Sasuser-sasjs\sas9.cfg
```

**Comment by jbodart-argenx** [comment]
the fact is, I already have a SAS_OPTIONS environment variable used by BASE SAS.

I tried to launch sasjs server from a batch file that modifies the environment variable SAS_OPTIONS as desired, but when I try to submit code I get messages like 
`
session crashed 20220908162148-40055-1662654108706 Error: Command failed: C:\Program Files\SASHome\SASFoundation\9.4\sas.exe -SYSIN C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\code.sas -LOG C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\log.log -PRINT C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\output.lst -WORK C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706 -AUTOEXEC C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\autoexec.sas -nologo -nosplash -icon -nodms -noterminal -nostatuswin -SASINITIALFOLDER C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706
`

**Comment by allanbowe** [comment]
Hmm.  I wonder if there are some conflicting settings in your config file?

What happens if you try to run that command directly?

```
C:\Program Files\SASHome\SASFoundation\9.4\sas.exe -SYSIN C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\code.sas -LOG C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\log.log -PRINT C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\output.lst -WORK C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706 -nologo -nosplash -icon -nodms -noterminal -nostatuswin -SASINITIALFOLDER C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706
```

Note - the autoexec is removed from that command due to a vagarity in how we [launch sessions](https://server.sasjs.io/sessions/).

**Comment by allanbowe** [comment]
If it would help your use case, we could look to add the config file location as a first class option setting.  

From experience though it can cause problems (which I suspect _might_ be the issue here) if the `.cfg` settings conflict with the command line (or environment var) settings.

**Comment by jbodart-argenx** [comment]
The command  
**"**C:\Program Files\SASHome\SASFoundation\9.4\sas.exe**"** -SYSIN C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\code.sas -LOG C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\log.log -PRINT C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706\output.lst -WORK C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706 -nologo -nosplash -icon -nodms -noterminal -nostatuswin -SASINITIALFOLDER C:\Users\jbodart\tools\sasjs-0.19.0\sasjs_root\sessions\20220908162148-40055-1662654108706 **&& echo ok**
seems to launch something and to close it within the next second, and writes ok to the terminal.

**Comment by jbodart-argenx** [comment]
I ended up starting my base SAS session with a non-default SASUSER setting, and let sasjs start its SAS session using the default SASUSER, that prevented conflicts.

**Comment by allanbowe** [comment]
I've created an issue in the sasjs/server repo to support a configurable config file:  https://github.com/sasjs/server/issues/278

I'll close this one as it appears to have been figured out, but feel free to continue the conversation if this is not the case.
